---
php_enable_webserver: false
php_fpm_state: stopped
php_fpm_enabled_on_boot: false
php_fpm_listen: "9000"  # We listen on all interfaces
php_fpm_listen_allowed_clients: ""
php_enable_php_fpm: true
mysql_python_package_debian: python3-mysqldb
