---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: testk8smoodle-db
  namespace: default
spec:
  teamId: "testk8smoodle"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    moodle-user:  # database owner
    - createdb
  databases:
    moodle-db: moodle-user  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "10"
