---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: testk8smoodle-db
  namespace: default
spec:
  teamId: "testk8smoodle"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    moodleuser:  # database owner
    - createdb
  databases:
    moodledb: moodleuser  # dbname: owner / avoid special chars
  preparedDatabases:
    bar: {}
  postgresql:
    version: "10"
