---
# Source: moodle-k8s/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testk8smoodle-moodle-k8s
  labels:
    helm.sh/chart: moodle-k8s-0.1.0
    app.kubernetes.io/name: moodle-k8s
    app.kubernetes.io/instance: testk8smoodle
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
